"""empty message

Revision ID: 490a261d5b78
Revises: 76539f91cf78
Create Date: 2020-02-18 15:43:35.179146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490a261d5b78'
down_revision = '76539f91cf78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
